---
host :
  # 绑定域名
  - "0.0.0.0"
#是否为调试模式,发布前请关闭调试模式
debug : true
# 使用伪静态
rewrite: false
# 应用模式
mode: mvc
# 项目名
app : cleanPHP
# 项目升级次数
verCode : 1
# 项目版本名称
verName : 1.0.0
# 日志有效期(天)
logValidTime : 30
# 安装程序模块名
install :


