---
# 数据库信息配置
master: "\n"
  type: mysql  # 数据库类型，支持mysql、sqlite2、sqlite3
  host: localhost  # 数据库地址
  username: root  # 数据库用户名
  password: toor  # 数据库密码
  port: 3306  # 数据库端口
  db: test  # 数据库库名
  charset: utf-8 # 数据库编码

sqlite: "\n"
  type: sqlite3  # 数据库类型，支持mysql、sqlite2、sqlite3
  host: ./storage/sql/1.db  # 数据库地址
  username:   # 数据库用户名
  password:   # 数据库密码
  port:   # 数据库端口
  db:   # 数据库库名
  charset: utf-8 # 数据库编码
